version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped



    environment:
      DB_HOST: db
      DB_USER: perfex
      DB_PASS: ${DB_PASS}
      DB_NAME: perfex_db

    depends_on:
      - db

    networks:
      - perfex-net
      - dokploy-network
      - default

    labels:
      - traefik.http.routers.perfex-crm-fi0xyz-2-web.rule=Host(`crm.supportzone.ae`)
      - traefik.http.routers.perfex-crm-fi0xyz-2-web.entrypoints=web
      - traefik.http.services.perfex-crm-fi0xyz-2-web.loadbalancer.server.port=80
      - traefik.http.routers.perfex-crm-fi0xyz-2-web.service=perfex-crm-fi0xyz-2-web
      - traefik.http.routers.perfex-crm-fi0xyz-2-web.middlewares=redirect-to-https@file

      - traefik.http.routers.perfex-crm-fi0xyz-2-websecure.rule=Host(`crm.supportzone.ae`)
      - traefik.http.routers.perfex-crm-fi0xyz-2-websecure.entrypoints=websecure
      - traefik.http.services.perfex-crm-fi0xyz-2-websecure.loadbalancer.server.port=80
      - traefik.http.routers.perfex-crm-fi0xyz-2-websecure.service=perfex-crm-fi0xyz-2-websecure
      - traefik.http.routers.perfex-crm-fi0xyz-2-websecure.tls.certresolver=letsencrypt

      - traefik.docker.network=dokploy-network
      - traefik.enable=true

  db:
    image: mariadb:10.11

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: perfex_db
      MYSQL_USER: perfex
      MYSQL_PASSWORD: ${DB_PASS}

    volumes:
      - db_data:/var/lib/mysql

    networks:
      - perfex-net

volumes:
  db_data:



networks:
  perfex-net:
    driver: overlay
    attachable: true

  dokploy-network:
    external: true